/*
 * -------------------------------------------------------------
 *  Generated by: SDK Generator
 *  Author      : projectilegravity & 48ix
 *  Timestamp   : 2026-06-28 15:38:49
 *  Game        : Fortnite
 *  Version     : ++Fortnite+Release-41.10-CL-55227503
 *  File        : class_offsets.h
 * -------------------------------------------------------------
 */

#pragma once
#include <cstdint>

namespace SDK
{

	struct Actor
	{
	public:
		static const uint32_t RootComponent = 0x1b0; // [Size: 0x8] [Property: ObjectProperty]
	};

	struct Character
	{
	public:
		static const uint32_t Mesh = 0x2f0; // [Size: 0x8] [Property: ObjectProperty]
		static const uint32_t bIsCrouched = 0x430; // [Size: 0x1] [Property: BoolProperty] [Mask: 0x2] [Bit: 1]
	};

	struct FortItemDefinition
	{
	public:
		static const uint32_t ItemType = 0xa0; // [Size: 0x1] [Property: EnumProperty]
		static const uint32_t PrimaryAssetIdItemTypeOverride = 0xa1; // [Size: 0x1] [Property: EnumProperty]
	};

	struct FortPawn
	{
	public:
		static const uint32_t bIsDying = 0x720; // [Size: 0x1] [Property: BoolProperty] [Mask: 0x20] [Bit: 5]
		static const uint32_t bIsDBNO = 0x849; // [Size: 0x1] [Property: BoolProperty] [Mask: 0x80] [Bit: 7]
		static const uint32_t CurrentWeapon = 0x998; // [Size: 0x8] [Property: ObjectProperty]
	};

	struct FortPickup
	{
	public:
		static const uint32_t PrimaryPickupItemEntry = 0x368; // [Size: 0x98] [Property: StructProperty]
	};

	struct FortPlayerController
	{
	public:
		static const uint32_t TargetedFortPawn = 0x1630; // [Size: 0x8] [Property: ObjectProperty]
		static const uint32_t LocationUnderReticle = 0x2080; // [Size: 0x18] [Property: StructProperty]
	};

	struct FortPlayerPawnAthena
	{
	public:
		static const uint32_t bIsSliding = 0x723; // [Size: 0x1] [Property: BoolProperty] [Mask: 0x10] [Bit: 4]
		static const uint32_t bIsSkydiving = 0x216f; // [Size: 0x1] [Property: BoolProperty] [Mask: 0x1] [Bit: 0]
	};

	struct FortPlayerState
	{
	public:
		static const uint32_t Platform = 0x400; // [Size: 0x10] [Property: StrProperty]
	};

	struct FortPlayerStateAthena
	{
	public:
		static const uint32_t TeamIndex = 0xf11; // [Size: 0x1] [Property: ByteProperty]
		static const uint32_t KillScore = 0xf28; // [Size: 0x4] [Property: IntProperty]
	};

	struct FortPlayerStateComponent_Habanero
	{
	public:
		static const uint32_t RankedProgress = 0xd8; // [Size: 0x20] [Property: StructProperty]
	};

	struct FortWeapon
	{
	public:
		static const uint32_t bIsReloadingWeapon = 0x379; // [Size: 0x1] [Property: BoolProperty] [Mask: 0x1] [Bit: 0]
		static const uint32_t WeaponData = 0x630; // [Size: 0x8] [Property: ObjectProperty]
		static const uint32_t AmmoCount = 0x10a4; // [Size: 0x4] [Property: IntProperty]
	};

	struct GameInstance
	{
	public:
		static const uint32_t LocalPlayers = 0x38; // [Size: 0x10] [Property: ArrayProperty]
	};

	struct GameStateBase
	{
	public:
		static const uint32_t PlayerArray = 0x288; // [Size: 0x10] [Property: ArrayProperty]
	};

	struct Pawn
	{
	public:
		static const uint32_t PlayerState = 0x290; // [Size: 0x8] [Property: ObjectProperty]
	};

	struct PlayerController
	{
	public:
		static const uint32_t AcknowledgedPawn = 0x318; // [Size: 0x8] [Property: ObjectProperty]
		static const uint32_t NetConnection = 0x4a8; // [Size: 0x8] [Property: ObjectProperty]
	};

	struct PlayerState
	{
	public:
		static const uint32_t bIsABot = 0x27a; // [Size: 0x1] [Property: BoolProperty] [Mask: 0x8] [Bit: 3]
		static const uint32_t PawnPrivate = 0x2e8; // [Size: 0x8] [Property: ObjectProperty]
	};

	struct SceneComponent
	{
	public:
		static const uint32_t RelativeLocation = 0x140; // [Size: 0x18] [Property: StructProperty]
		static const uint32_t RelativeRotation = 0x158; // [Size: 0x18] [Property: StructProperty]
		static const uint32_t ComponentVelocity = 0x188; // [Size: 0x18] [Property: StructProperty]
		static const uint32_t bComponentToWorldUpdated = 0x1a0; // [Size: 0x1] [Property: BoolProperty] [Mask: 0x1] [Bit: 0]
	};

	struct World
	{
	public:
		static const uint32_t PersistentLevel = 0x38; // [Size: 0x8] [Property: ObjectProperty]
		static const uint32_t NetDriver = 0x40; // [Size: 0x8] [Property: ObjectProperty]
		static const uint32_t GameState = 0x1d0; // [Size: 0x8] [Property: ObjectProperty]
		static const uint32_t OwningGameInstance = 0x248; // [Size: 0x8] [Property: ObjectProperty]
	};

	struct Player
	{
	public:
		static const uint32_t PlayerController = 0x30; // [Size: 0x8] [Property: ObjectProperty]
	};

}

